export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  UserService: Symbol.for('UserService'),
  UserModel: Symbol.for('UserModel'),
  FavoriteOfferModel: Symbol.for('FavoriteOfferModel'),
  FavoriteOfferService: Symbol.for('FavoriteOfferService'),
  PremiumOfferModel: Symbol.for('PremiumOfferModel'),
  PremiumOfferService: Symbol.for('PremiumOfferService'),
  RentalOfferModel: Symbol.for('RentalOfferModel'),
  RentalOfferService: Symbol.for('RentalOfferService'),
  RatingModel: Symbol.for('RatingModel'),
  RatingService: Symbol.for('RatingService'),
} as const;
